exclude: ["doxygen", "jekyll"]

theme: jekyll-theme-minimal
logo: ubirch-logo.png
title: Ubirch Protocol Python
subtitle: Documentation and Examples
description: Official Documentation

plugins:
  - jekyll-optional-front-matter

plugins_dir         : jekyll/_plugins
layouts_dir         : jekyll/_layouts
includes_dir        : jekyll/_includes
sass:
  sass_dir: jekyll/_sass

# Some configuration settings cannot be changed for GitHub Pages sites:
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
